In [1]:
import tensorflow as tf

print(tf.__version__)

2024-02-15 19:17:07.617524: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-02-15 19:17:07.774680: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-02-15 19:17:08.319866: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-15 19:17:08.319945: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-15 19:17:08.409296: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to

2.15.0


In [2]:
scalar = tf.constant(7)
scalar, scalar.ndim

2024-02-15 19:17:10.893512: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-02-15 19:17:10.893944: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2256] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


(<tf.Tensor: shape=(), dtype=int32, numpy=7>, 0)

In [3]:
vector = tf.constant([10, 20])
vector, vector.ndim

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>, 1)

In [4]:
matrix = tf.constant([[10, 20], [30, 40]])
matrix, matrix.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 20],
        [30, 40]], dtype=int32)>,
 2)

In [5]:
matrix_2 = tf.constant([[1,2], [3,4], [5,6]], dtype=tf.float32)
matrix_2, matrix_2.ndim

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=float32)>,
 2)

In [6]:
changeable_tensor = tf.Variable([1, 2])
unchangeable_tensor = tf.constant([1, 2])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>)

In [7]:
changeable_tensor[0].assign(11)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([11,  2], dtype=int32)>

In [8]:
unchangeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [9]:
random_t_1 = tf.random.Generator.from_seed(42)
random_t_1 = random_t_1.normal(shape=(4, 2))
random_t_1

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646]], dtype=float32)>

In [10]:
random_t_2 = tf.random.Generator.from_seed(42)
random_t_2 = random_t_2.normal(shape=(4, 2))
random_t_2

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646]], dtype=float32)>

In [11]:
random_t_1 == random_t_2

<tf.Tensor: shape=(4, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])>

In [12]:
random_t_1 == matrix_2

<tf.Tensor: shape=(), dtype=bool, numpy=False>

In [13]:
tf.random.shuffle(random_t_1)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [-0.23193763, -1.8107855 ],
       [ 0.07595026, -1.2573844 ],
       [ 0.09988727, -0.50998646]], dtype=float32)>

In [14]:
tf.ones([2, 2, 2]), tf.zeros([2, 2, 2])

(<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
 array([[[1., 1.],
         [1., 1.]],
 
        [[1., 1.],
         [1., 1.]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
 array([[[0., 0.],
         [0., 0.]],
 
        [[0., 0.],
         [0., 0.]]], dtype=float32)>)

In [15]:
import numpy as np

array_1 = np.arange(1, 25)

print(tf.constant(array_1))
print(tf.constant(array_1, shape=(1, 2, 12)))
print(tf.constant(array_1, shape=(3, 8)))

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,), dtype=int64)
tf.Tensor(
[[[ 1  2  3  4  5  6  7  8  9 10 11 12]
  [13 14 15 16 17 18 19 20 21 22 23 24]]], shape=(1, 2, 12), dtype=int64)
tf.Tensor(
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]], shape=(3, 8), dtype=int64)


In [16]:
print(random_t_1.shape)
print(random_t_1.ndim)
print(random_t_1.shape)
print(tf.size(random_t_1))
print(random_t_1[:1])

(4, 2)
2
(4, 2)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor([[-0.7565803  -0.06854702]], shape=(1, 2), dtype=float32)


Adicionar dimensões ao tensor

In [17]:
# ... == :, :, :, :
print(random_t_1[..., tf.newaxis])
print(tf.expand_dims(random_t_1, axis=-1))

tf.Tensor(
[[[-0.7565803 ]
  [-0.06854702]]

 [[ 0.07595026]
  [-1.2573844 ]]

 [[-0.23193763]
  [-1.8107855 ]]

 [[ 0.09988727]
  [-0.50998646]]], shape=(4, 2, 1), dtype=float32)
tf.Tensor(
[[[-0.7565803 ]
  [-0.06854702]]

 [[ 0.07595026]
  [-1.2573844 ]]

 [[-0.23193763]
  [-1.8107855 ]]

 [[ 0.09988727]
  [-0.50998646]]], shape=(4, 2, 1), dtype=float32)


In [18]:
tf.expand_dims(random_t_1, axis=0)

<tf.Tensor: shape=(1, 4, 2), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646]]], dtype=float32)>

Tensor operations

In [19]:
vector, matrix

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 20],
        [30, 40]], dtype=int32)>)

In [20]:
print(matrix + 10)
print(matrix - 10)
print(matrix * 10)
print(matrix / 10)
print(matrix // 10)

tf.Tensor(
[[20 30]
 [40 50]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 0 10]
 [20 30]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100 200]
 [300 400]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float64)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [21]:
print(tf.multiply(matrix, matrix))
print(tf.multiply(matrix, 10))
print(tf.multiply(matrix, vector))
print(tf.multiply(vector, matrix))

tf.Tensor(
[[ 100  400]
 [ 900 1600]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100 200]
 [300 400]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100 400]
 [300 800]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100 400]
 [300 800]], shape=(2, 2), dtype=int32)


In [22]:
print(tf.add(matrix, matrix))
print(tf.add(matrix, vector))

tf.Tensor(
[[20 40]
 [60 80]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[20 40]
 [40 60]], shape=(2, 2), dtype=int32)


Matrix multiplication

In [23]:
print(tf.matmul(matrix, matrix))
print(matrix @ matrix)

print(tf.matmul(matrix, vector[..., tf.newaxis]))
print(tf.matmul(matrix[..., tf.newaxis], vector[..., tf.newaxis][..., tf.newaxis]))

tf.Tensor(
[[ 700 1000]
 [1500 2200]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 700 1000]
 [1500 2200]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 500]
 [1100]], shape=(2, 1), dtype=int32)
tf.Tensor(
[[[100]
  [200]]

 [[600]
  [800]]], shape=(2, 2, 1), dtype=int32)


In [24]:
print(random_t_1, random_t_2)
print(random_t_1 @ tf.reshape(random_t_2, shape=(2, 4)))
print(tf.reshape(random_t_1, shape=(1, 4, 2)) @ tf.reshape(random_t_2, shape=(4, 2, 1)))
print(tf.reshape(random_t_1, shape=(1, 2, 4)) @ tf.reshape(random_t_2, shape=(2, 4, 1)))
#print(tf.reshape(random_t_1, shape=(4, 2, 1)) @ tf.reshape(random_t_2, shape=(2, 1, 4)))


tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]
 [ 0.09988727 -0.50998646]], shape=(4, 2), dtype=float32) tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]
 [ 0.09988727 -0.50998646]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[ 0.5883124   0.17598528 -0.06430944  0.9862703 ]
 [ 0.2341723   2.2716475  -0.11982825  0.5457503 ]
 [ 0.59546876  3.294843   -0.19849014  1.2151109 ]
 [ 0.04271232  0.91662914 -0.04335469  0.13448949]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[[ 0.57711244]
  [ 0.02872748]
  [ 0.2996034 ]
  [-0.04061469]]

 [[ 0.02872748]
  [ 1.586784  ]
  [ 2.2592378 ]
  [ 0.6488355 ]]

 [[ 0.2996034 ]
  [ 2.2592378 ]
  [ 3.3327394 ]
  [ 0.9003085 ]]

 [[-0.04061469]
  [ 0.6488355 ]
  [ 0.9003085 ]
  [ 0.27006367]]], shape=(4, 4, 1), dtype=float32)
tf.Tensor(
[[[2.1638963]
  [0.9484389]]

 [[0.9484389]
  [3.6028032]]], shape=(2, 2, 1), dtype=float32)


In [25]:
tf.tensordot(matrix, matrix, axes=0)
tf.tensordot(random_t_1, random_t_1, axes=0)

<tf.Tensor: shape=(4, 2, 4, 2), dtype=float32, numpy=
array([[[[ 0.57241374,  0.05186132],
         [-0.05746247,  0.95131224],
         [ 0.17547944,  1.3700047 ],
         [-0.07557274,  0.3858457 ]],

        [[ 0.05186132,  0.00469869],
         [-0.00520616,  0.08618996],
         [ 0.01589863,  0.12412395],
         [-0.00684697,  0.03495805]]],


       [[[-0.05746247, -0.00520616],
         [ 0.00576844, -0.09549867],
         [-0.01761572, -0.13752963],
         [ 0.00758646, -0.0387336 ]],

        [[ 0.95131224,  0.08618996],
         [-0.09549867,  1.5810156 ],
         [ 0.29163477,  2.2768536 ],
         [-0.12559669,  0.641249  ]]],


       [[[ 0.17547944,  0.01589863],
         [-0.01761572,  0.29163477],
         [ 0.05379507,  0.41998932],
         [-0.02316762,  0.11828505]],

        [[ 1.3700047 ,  0.12412395],
         [-0.13752963,  2.2768536 ],
         [ 0.41998932,  3.2789443 ],
         [-0.18087442,  0.9234761 ]]],


       [[[-0.07557274, -0.00684697],
   

In [26]:
print(tf.reduce_min(random_t_1))
print(tf.reduce_max(random_t_1))
print(tf.reduce_mean(random_t_1))
print(tf.reduce_sum(random_t_1))
print(tf.math.reduce_std(random_t_1))
print(tf.math.reduce_variance(random_t_1))

tf.Tensor(-1.8107855, shape=(), dtype=float32)
tf.Tensor(0.09988727, shape=(), dtype=float32)
tf.Tensor(-0.557423, shape=(), dtype=float32)
tf.Tensor(-4.459384, shape=(), dtype=float32)
tf.Tensor(0.6404038, shape=(), dtype=float32)
tf.Tensor(0.41011703, shape=(), dtype=float32)


In [27]:
#print(random_t_1[tuple(tf.argmin(random_t_1))])
print(tf.argmin(random_t_1))

tf.Tensor([0 2], shape=(2,), dtype=int64)


In [28]:
tf.squeeze(random_t_1)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646]], dtype=float32)>

In [29]:
# list = ["a", "b", "c", "d"]
list = [1, 2, 3, 4]

tf.one_hot(list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [30]:
bla = tf.range(1, 10)
tf.square(bla), tf.sqrt(tf.cast(bla, dtype=tf.float32)), tf.math.log(tf.cast(bla, dtype=tf.float32))

(<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
        2.6457512, 2.828427 , 3.       ], dtype=float32)>,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
        1.9459102, 2.0794415, 2.1972246], dtype=float32)>)

In [31]:
# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y


x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))

tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [32]:
from tensorflow.python.client import device_lib

def get_available_devices():
    local_device_protos = device_lib.list_local_devices()
    return [x.name for x in local_device_protos]

print(tf.config.list_physical_devices('GPU'))
print(get_available_devices())

[]
['/device:CPU:0']


2024-02-15 19:17:11.453102: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-02-15 19:17:11.453187: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2256] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [33]:
!nvidia-smi

Thu Feb 15 19:17:11 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.154.05             Driver Version: 535.154.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3060        Off | 00000000:01:00.0  On |                  N/A |
| 30%   36C    P2              39W / 170W |    498MiB / 12288MiB |     12%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--