In [28]:
import tensorflow as tf

print(tf.__version__)

2.15.0


In [29]:
scalar = tf.constant(7)
scalar, scalar.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=7>, 0)

In [30]:
vector = tf.constant([10, 20])
vector, vector.ndim

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>, 1)

In [31]:
matrix = tf.constant([[10, 20], [30, 40]])
matrix, matrix.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 20],
        [30, 40]], dtype=int32)>,
 2)

In [32]:
matrix_2 = tf.constant([[1,2], [3,4], [5,6]], dtype=tf.float32)
matrix_2, matrix_2.ndim

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=float32)>,
 2)

In [33]:
changeable_tensor = tf.Variable([1, 2])
unchangeable_tensor = tf.constant([1, 2])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>)

In [34]:
changeable_tensor[0].assign(11)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([11,  2], dtype=int32)>

In [35]:
unchangeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [36]:
random_t_1 = tf.random.Generator.from_seed(42)
random_t_1 = random_t_1.normal(shape=(4, 2))
random_t_1

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646]], dtype=float32)>

In [37]:
random_t_2 = tf.random.Generator.from_seed(42)
random_t_2 = random_t_2.normal(shape=(4, 2))
random_t_2

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646]], dtype=float32)>

In [38]:
random_t_1 == random_t_2

<tf.Tensor: shape=(4, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])>

In [39]:
random_t_1 == matrix_2

<tf.Tensor: shape=(), dtype=bool, numpy=False>

In [40]:
tf.random.shuffle(random_t_1)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[-0.23193763, -1.8107855 ],
       [-0.7565803 , -0.06854702],
       [ 0.09988727, -0.50998646],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

In [41]:
tf.ones([2, 2, 2]), tf.zeros([2, 2, 2])

(<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
 array([[[1., 1.],
         [1., 1.]],
 
        [[1., 1.],
         [1., 1.]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
 array([[[0., 0.],
         [0., 0.]],
 
        [[0., 0.],
         [0., 0.]]], dtype=float32)>)

In [42]:
import numpy as np

array_1 = np.arange(1, 25)

print(tf.constant(array_1))
print(tf.constant(array_1, shape=(1, 2, 12)))
print(tf.constant(array_1, shape=(3, 8)))

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,), dtype=int64)
tf.Tensor(
[[[ 1  2  3  4  5  6  7  8  9 10 11 12]
  [13 14 15 16 17 18 19 20 21 22 23 24]]], shape=(1, 2, 12), dtype=int64)
tf.Tensor(
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]], shape=(3, 8), dtype=int64)


In [43]:
print(random_t_1.shape)
print(random_t_1.ndim)
print(random_t_1.shape)
print(tf.size(random_t_1))
print(random_t_1[:1])

(4, 2)
2
(4, 2)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor([[-0.7565803  -0.06854702]], shape=(1, 2), dtype=float32)


Adicionar dimensões ao tensor

In [44]:
# ... == :, :, :, :
print(random_t_1[..., tf.newaxis])
print(tf.expand_dims(random_t_1, axis=-1))

tf.Tensor(
[[[-0.7565803 ]
  [-0.06854702]]

 [[ 0.07595026]
  [-1.2573844 ]]

 [[-0.23193763]
  [-1.8107855 ]]

 [[ 0.09988727]
  [-0.50998646]]], shape=(4, 2, 1), dtype=float32)
tf.Tensor(
[[[-0.7565803 ]
  [-0.06854702]]

 [[ 0.07595026]
  [-1.2573844 ]]

 [[-0.23193763]
  [-1.8107855 ]]

 [[ 0.09988727]
  [-0.50998646]]], shape=(4, 2, 1), dtype=float32)


In [45]:
tf.expand_dims(random_t_1, axis=0)

<tf.Tensor: shape=(1, 4, 2), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646]]], dtype=float32)>

Tensor operations

In [46]:
vector, matrix

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 20],
        [30, 40]], dtype=int32)>)

In [47]:
print(matrix + 10)
print(matrix - 10)
print(matrix * 10)
print(matrix / 10)
print(matrix // 10)

tf.Tensor(
[[20 30]
 [40 50]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 0 10]
 [20 30]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100 200]
 [300 400]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float64)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [48]:
print(tf.multiply(matrix, matrix))
print(tf.multiply(matrix, 10))
print(tf.multiply(matrix, vector))
print(tf.multiply(vector, matrix))

tf.Tensor(
[[ 100  400]
 [ 900 1600]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100 200]
 [300 400]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100 400]
 [300 800]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100 400]
 [300 800]], shape=(2, 2), dtype=int32)


In [49]:
print(tf.add(matrix, matrix))
print(tf.add(matrix, vector))

tf.Tensor(
[[20 40]
 [60 80]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[20 40]
 [40 60]], shape=(2, 2), dtype=int32)


Matrix multiplication

In [50]:
print(tf.matmul(matrix, matrix))
print(matrix @ matrix)

print(tf.matmul(matrix, vector[..., tf.newaxis]))
print(tf.matmul(matrix[..., tf.newaxis], vector[..., tf.newaxis][..., tf.newaxis]))

tf.Tensor(
[[ 700 1000]
 [1500 2200]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 700 1000]
 [1500 2200]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 500]
 [1100]], shape=(2, 1), dtype=int32)
tf.Tensor(
[[[100]
  [200]]

 [[600]
  [800]]], shape=(2, 2, 1), dtype=int32)


In [51]:
print(random_t_1, random_t_2)
print(random_t_1 @ tf.reshape(random_t_2, shape=(2, 4)))
print(tf.reshape(random_t_1, shape=(1, 4, 2)) @ tf.reshape(random_t_2, shape=(4, 2, 1)))
print(tf.reshape(random_t_1, shape=(1, 2, 4)) @ tf.reshape(random_t_2, shape=(2, 4, 1)))
#print(tf.reshape(random_t_1, shape=(4, 2, 1)) @ tf.reshape(random_t_2, shape=(2, 1, 4)))


tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]
 [ 0.09988727 -0.50998646]], shape=(4, 2), dtype=float32) tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193763 -1.8107855 ]
 [ 0.09988727 -0.50998646]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[ 0.5883124   0.17598528 -0.06430944  0.9862703 ]
 [ 0.2341723   2.2716475  -0.11982825  0.5457503 ]
 [ 0.59546876  3.294843   -0.19849014  1.2151109 ]
 [ 0.04271232  0.91662914 -0.04335469  0.13448949]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[[ 0.57711244]
  [ 0.02872748]
  [ 0.2996034 ]
  [-0.04061469]]

 [[ 0.02872748]
  [ 1.586784  ]
  [ 2.2592378 ]
  [ 0.6488355 ]]

 [[ 0.2996034 ]
  [ 2.2592378 ]
  [ 3.3327394 ]
  [ 0.9003085 ]]

 [[-0.04061469]
  [ 0.6488355 ]
  [ 0.9003085 ]
  [ 0.27006367]]], shape=(4, 4, 1), dtype=float32)
tf.Tensor(
[[[2.1638963]
  [0.9484389]]

 [[0.9484389]
  [3.6028032]]], shape=(2, 2, 1), dtype=float32)


In [53]:
tf.tensordot(matrix, matrix, axes=0)
tf.tensordot(random_t_1, random_t_1, axes=0)

<tf.Tensor: shape=(4, 2, 4, 2), dtype=float32, numpy=
array([[[[ 0.57241374,  0.05186132],
         [-0.05746247,  0.95131224],
         [ 0.17547944,  1.3700047 ],
         [-0.07557274,  0.3858457 ]],

        [[ 0.05186132,  0.00469869],
         [-0.00520616,  0.08618996],
         [ 0.01589863,  0.12412395],
         [-0.00684697,  0.03495805]]],


       [[[-0.05746247, -0.00520616],
         [ 0.00576844, -0.09549867],
         [-0.01761572, -0.13752963],
         [ 0.00758646, -0.0387336 ]],

        [[ 0.95131224,  0.08618996],
         [-0.09549867,  1.5810156 ],
         [ 0.29163477,  2.2768536 ],
         [-0.12559669,  0.641249  ]]],


       [[[ 0.17547944,  0.01589863],
         [-0.01761572,  0.29163477],
         [ 0.05379507,  0.41998932],
         [-0.02316762,  0.11828505]],

        [[ 1.3700047 ,  0.12412395],
         [-0.13752963,  2.2768536 ],
         [ 0.41998932,  3.2789443 ],
         [-0.18087442,  0.9234761 ]]],


       [[[-0.07557274, -0.00684697],
   

In [61]:
print(tf.reduce_min(random_t_1))
print(tf.reduce_max(random_t_1))
print(tf.reduce_mean(random_t_1))
print(tf.reduce_sum(random_t_1))
print(tf.math.reduce_std(random_t_1))
print(tf.math.reduce_variance(random_t_1))

tf.Tensor(-1.8107855, shape=(), dtype=float32)
tf.Tensor(0.09988727, shape=(), dtype=float32)
tf.Tensor(-0.557423, shape=(), dtype=float32)
tf.Tensor(-4.459384, shape=(), dtype=float32)
tf.Tensor(0.6404038, shape=(), dtype=float32)
tf.Tensor(0.41011703, shape=(), dtype=float32)


In [70]:
#print(random_t_1[tuple(tf.argmin(random_t_1))])
print(tf.argmin(random_t_1))

tf.Tensor([0 2], shape=(2,), dtype=int64)


In [69]:
tf.squeeze(random_t_1)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646]], dtype=float32)>